# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raajay's Personal Webpage
email: raajay at cs dot wisc dot edu
description: > # this means to ignore newlines until "baseurl:"
    A few random thoughts...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pages.cs.wisc.edu/~raajay" # the base hostname & protocol for your site
twitter_username: raajay
github_username:  raajay

# Build settings
markdown: kramdown
